### PR TITLE
feat: add login and logout screens

### PR DESCRIPTION
**Pull request by Aditi0505**
# Description
- Added Login and Signup screens
- fixed link references 
- Added fixed position to footer

# Screenshots
image
image

### CODE REVIEW

**Review by anupkgurung — APPROVED** [review]
Suggestion login and sign up doesn't necessarily have to be a card component.

**Comment by Aditi0505** [comment]
@anupkgurung I have placed the form inside the card component to use it's styling. Is this a right approach?

**Review by Naveenchandar — APPROVED** [review]
Looks good

**Comment by anupkgurung** [comment]
> Suggestion login and sign up doesn't necessarily have to be a card component.



> @anupkgurung I have placed the form inside the card component to use it's styling. Is this a right approach?

oh i think i did not see that it should be okay than. Not sure about the right approach though. However you can always refer any web app.

**Pull request merged**
